version: 0.0.{build}
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- ps: nuget restore md.sln -verbosity quiet
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: normal
after_build:
- ps: nuget pack md.stdl\md.stdl.csproj -Version %appveyor_build_version%
deploy:
- provider: NuGet
  api_key:
    secure: b4Ec1SXgC2n9ZSaGOdEqDsS3r2mbmmjbzKPpAqybLkk9f/8ZXHNUaE5ImKFw1egj